### ISSUE TITLE
Using as documentation

### ISSUE THREAD

**Issue by bradmartin333** [mitxela/recursive#2]
Hey! I'm glad to see action here.

Things went well with standalone.
I'm now hoping to use it as source controlled documentation within my GitHub pages.

What is the best/easiest way to do that?
Source control a .JSON and load it with onload() ?
Or just use the standalone?

**Comment by mitxela** [comment]
Yeah you could just track the JSON file. If you pretty-print the JSON, git would be able to show more meaningful diffs, although you'd still have the problem that javascript objects aren't ordered, so loading and saving the file could show things being re-ordered, even when nothing's changed.

If that turns out to be a problem, you could have a custom json stringify that sorts the objects predictably.

I've recently been adding the "deltaHistory" / activity stuff. So the right sidebar shows a list of changes to the file, and as you undo/redo it scrolls through them. I'm not sure what direction I want to take it, potentially the saved data could include all of the activity right from the very beginning, like a CAD design. I'm not sure that's what I want for a notes program though. Another question is if I ever make a server with collaborative editing, whether the undo/redo history should be separate to a server activity log that interleaves different people's changes.

Another thing I plan to eventually add is a read-only mode.

**Comment by bradmartin333** [comment]
**JSON**
I'm not sure what you mean by the re-ordering quite yet, but maybe I will run into it.

This works... but, is there a better way?
``` js
async function loadTree() {
  let fileData = await fetch('./tree.json');
  let jsonData = await fileData.json();
  lastStorage = localStorage.tree;
  localStorage.tree = JSON.stringify(jsonData.tree);
  if (lastStorage != localStorage.tree) {
    location.reload();
  }
}
loadTree();
```

I think the easiest way to update the JSON would be save a new one and replace the old one in the tracked dir, yeah? I think I remember filesync being something newish for browsers and out of scope.

**History**
I think the history bar looks and acts great, but I am not sure how I would use it at the moment. 

**Collab**
I enjoy it in something like Overleaf, but I could see a lot of required features to make it usable here. 
For instance, in Overleaf: 
> "Okay I am in `report/styles/structure.tex` on like 47, you see my cursor?"
>> "Hold on, scrolling... okay yeah"

But for recursive, you would need a sidebar with the active users and something like a jump to user button. I can't remember if Overleaf has that. Sounds pretty cool, though.

**Read-Only**
So it would essentially `pin` everything without losing the `pinned` state? Cool

**Comment by bradmartin333** [comment]
- hmm, I wasn't having the same results with reloadAll() or FileReader, but that's probably due to my JS abilities
- validTree() is always returning false within my added method, but I am okay with just trusting my tracked file
- pretty-print works perfectly!
- looking forward to what you come up with!
