### ISSUE TITLE
collab with tldraw?

### ISSUE THREAD

**Issue by bradmartin333** [mitxela/recursive#3]
https://github.com/tldraw/tldraw

**Comment by mitxela** [comment]
That's a pretty cool project. The UI seems well thought-out.

About a month after we last spoke, I had a stab at making a fully collaborative version of recursive. I didn't publish it but I got it about 95% of the way there. I've been using it exclusively to manage my own projects since then, although the only collaborative part I use is that I have it open on two laptops at once. Part of the reason I didn't publish it is that the server code is only proof-of-concept and not really written with security in mind.

I have a feeling that the only collaboration with tldraw that could happen is that they implement a recursive notes aspect to their project. My code is written in such an idiosyncratic way that it would probably scare away any collaborators.

I am definitely still working on recursive though, at some point I may polish up the server code and release it. But it's not something I want to publicly host until I put at least a little thought into the security aspect.
